# 11 - October - 2018
print()
print("Program to perform different basic File Operations")
print("_______________________________________________________________________")
print("\t\t\t\t\t\t1. Reading from File")
print("_______________________________________________________________________")
f = open('test.txt', 'r')
print(f.name)
print(f.mode)
print()
file_contents = f.read()
print(file_contents)
f.close()

print("_______________________________________________________________________")
print("\t\t\t\t\t\t2. Seek Operation on File")
print("_______________________________________________________________________")
f = open('test.txt', 'r')
size_to_read = 13
file_contents = f.read(size_to_read)
print(file_contents, end='')
f.seek(0)
print()
file_contents = f.read(size_to_read)
print(file_contents)
f.close()
print("_______________________________________________________________________")
print("\t\t\t\t\t\t3. Write into the File")
print("_______________________________________________________________________")
f1 = open('test2.txt', 'w')
f1.write('Test')
f1.close()
