import sqlite3

db = sqlite3.connect("Employees.sqlite")
print("Opened database successfully...!!!")
print("_"*80)
new_email = "newemail@update.com"
empid = input("Please enter id= ")
print("_"*80)
update_sql = "UPDATE employees SET email= '{}' WHERE empid= {}".format(new_email, empid)
print(update_sql)
update_cursor = db.cursor()
update_cursor.executescript(update_sql)
print("{} Rows updated".format(update_cursor.rowcount))
print("_"*80)
update_cursor.connection.commit()
update_cursor.close()
print()
for empid, name, age, email, salary in db.execute("SELECT * FROM Employees"):
    print("EMPID=", empid)
    print("NAME=", name)
    print("AGE=", age)
    print("EMAIL=", email)
    print("SALARY=", salary)
    print("-" * 20)
db.close()
